import type { Student } from './types';

export const INITIAL_SCORE = 0;

export const INITIAL_STUDENTS: Omit<Student, 'team'>[] = [
  { id: 1, name: 'Dơng Gur A Ne', score: INITIAL_SCORE },
  { id: 2, name: 'Đinh Thị Phương Anh', score: INITIAL_SCORE },
  { id: 3, name: 'Ngô Quốc Anh', score: INITIAL_SCORE },
  { id: 4, name: 'Dương Khánh Bảo', score: INITIAL_SCORE },
  { id: 5, name: 'Lê Thái Gia Bảo', score: INITIAL_SCORE },
  { id: 6, name: 'Nguyễn Quốc Bảo', score: INITIAL_SCORE },
  { id: 7, name: 'Phạm Đình Bảo', score: INITIAL_SCORE },
  { id: 8, name: 'Trần Đình Bảo', score: INITIAL_SCORE },
  { id: 9, name: 'Lê Vũ Khánh Băng', score: INITIAL_SCORE },
  { id: 10, name: 'Nguyễn Phạm Dân Du', score: INITIAL_SCORE },
  { id: 11, name: 'Nguyễn Ngô Hồng Duyên', score: INITIAL_SCORE },
  { id: 12, name: 'Lê Trần Tiến Đạt', score: INITIAL_SCORE },
  { id: 13, name: 'Nguyễn Thành Đạt', score: INITIAL_SCORE },
  { id: 14, name: 'Nguyễn Vũ Đăng Hải', score: INITIAL_SCORE },
  { id: 15, name: 'Sẳm Thanh Hải', score: INITIAL_SCORE },
  { id: 16, name: 'Mai Phước Hạnh', score: INITIAL_SCORE },
  { id: 17, name: 'Quang Minh Nhật Hào', score: INITIAL_SCORE },
  { id: 18, name: 'Nguyễn Hoàng', score: INITIAL_SCORE },
  { id: 19, name: 'Vũ Việt Hoàng', score: INITIAL_SCORE },
  { id: 20, name: 'Lê Nguyễn Gia Huy', score: INITIAL_SCORE },
  { id: 21, name: 'Trương Gia Huy', score: INITIAL_SCORE },
  { id: 22, name: 'Vòng Minh Huy', score: INITIAL_SCORE },
  { id: 23, name: 'Hoàng Phúc Khánh', score: INITIAL_SCORE },
  { id: 24, name: 'Kơ Să K\' Khin', score: INITIAL_SCORE },
  { id: 25, name: 'Hồ Quang Kiệt', score: INITIAL_SCORE },
  { id: 26, name: 'Lê Huỳnh Anh Kiệt', score: INITIAL_SCORE },
  { id: 27, name: 'K\' Lang', score: INITIAL_SCORE },
  { id: 28, name: 'Ngô Thị Lê', score: INITIAL_SCORE },
  { id: 29, name: 'Hà Khánh Linh', score: INITIAL_SCORE },
  { id: 30, name: 'Phùng Thiên Long', score: INITIAL_SCORE },
  { id: 31, name: 'Cil Pam Ha Luận', score: INITIAL_SCORE },
  { id: 32, name: 'Lý Hiểu Minh', score: INITIAL_SCORE },
  { id: 33, name: 'Nguyễn Ngọc Kim Ngân', score: INITIAL_SCORE },
  { id: 34, name: 'Trần Ngọc Yến Nhi', score: INITIAL_SCORE },
  { id: 35, name: 'K\' Nương', score: INITIAL_SCORE },
  { id: 36, name: 'Lưu Thượng Quyền', score: INITIAL_SCORE },
  { id: 37, name: 'Nguyễn Tấn Tài', score: INITIAL_SCORE },
  { id: 38, name: 'Phạm Lê Anh Tài', score: INITIAL_SCORE },
  { id: 39, name: 'Đàm Ngọc Thiện', score: INITIAL_SCORE },
  { id: 40, name: 'Lê Hữu Thịnh', score: INITIAL_SCORE },
  { id: 41, name: 'Lý Hưng Thịnh', score: INITIAL_SCORE },
  { id: 42, name: 'Lê Lương Tính', score: INITIAL_SCORE },
  { id: 43, name: 'Huỳnh Văn Trí', score: INITIAL_SCORE },
  { id: 44, name: 'Hùng Phương Thanh Trúc', score: INITIAL_SCORE },
  { id: 45, name: 'Ngô Đặng Quang Trung', score: INITIAL_SCORE },
  { id: 46, name: 'Hoàng Vinh Trường', score: INITIAL_SCORE },
  { id: 47, name: 'Hoàng Thái Tuấn', score: INITIAL_SCORE },
  { id: 48, name: 'Đào Thị Phương Uyên', score: INITIAL_SCORE },
  { id: 49, name: 'Trần Đức Chí Vĩnh', score: INITIAL_SCORE },
  { id: 50, name: 'Bạc Hoàng Vũ', score: INITIAL_SCORE },
  { id: 51, name: 'Phan Minh Vũ', score: INITIAL_SCORE },
  { id: 52, name: 'Huỳnh Ngọc Yên', score: INITIAL_SCORE },
];